INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('homepage_nemesys', '', 'nemesys homepage', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='homepage_nemesys'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='homepage_nemesys'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('community_nemesys', '', 'nemesys community', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='community_nemesys'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='community_nemesys'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('features_nemesys', '', 'nemesys features', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='features_nemesys'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='features_nemesys'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('contactus_nemesys', '', 'nemesys contactus', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contactus_nemesys'), 'send.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contactus_nemesys'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contactus_nemesys'), 'mail_contactus.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contactus_nemesys'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contactus_nemesys'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('download_nemesys', '', 'nemesys download', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_nemesys'), 'index.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_nemesys'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_nemesys'), 'popup_download.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_nemesys'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_nemesys'), 'init2.inc', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='search');
DELETE FROM template_disponibili WHERE dir_template='search';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('search', '', 'search', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_all.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_news.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init2.inc', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter');
DELETE FROM template_disponibili WHERE dir_template='newsletter';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('newsletter', '', 'newsletter', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter'), 'newsletter.asp', 1);
INSERT INTO `module_portal` (`keyword`, `descrizione`, `version`, `active`) VALUES ('nemesys-theme', 'nemesys theme installation', '1.5.5.3', '1');