	<div id="header">
		<div id="top-bar">
			<div id="top-bar-logo"><!--<a href="<%=base_url&Application("srt_default_server_name")&Application("baseroot")&"/default.asp"%>"><img src="<%=Application("baseroot")&"/common/img/logo.png"%>" hspace="2" vspace="0" border="0" align="left" alt="<%=lang.getTranslated("portal.commons.label.home_page")%>"></a>--></div>
			<div id="top-bar-search"><!-- #include virtual="/public/layout/addson/search/search_widget.inc" --></div>
			<div id="top-bar-lenguage"><!-- #include virtual="/public/layout/addson/langs/langs_widget.inc" --></div>
		</div>
		<div id="image-container">
			<div>
			<!--<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="900" height="210" id="header" align="middle">
			<param name="allowScriptAccess" value="sameDomain" />
			<param name="allowFullScreen" value="false" />
			<param name="FlashVars" value="prefisso=http://www.blackholenet.com/public/conf/immagini-header.xml">
			<param name="movie" value="http://www.blackholenet.com/common/swf/header.swf" />
			<param name="quality" value="high" />
			<param name="wmode" value="transparent" />
			<param name="bgcolor" value="#ffffff" />	
			<embed src="http://www.blackholenet.com/common/swf/header.swf" FlashVars="prefisso=http://www.blackholenet.com/public/conf/immagini-header.xml" quality="high" wmode="transparent" bgcolor="#ffffff" width="900" height="210" name="header" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer_it" />
			</object>-->
			</div>		
		</div>
	</div>