	<div id="header">
		<div id="top-bar">
			<div id="top-bar-logo">&nbsp;</div>
			<div id="top-bar-search"><!-- #include virtual="/public/layout/addson/search/search_widget.inc" --></div>
			<div id="top-bar-lenguage"><!-- #include virtual="/public/layout/addson/langs/langs_widget.inc" --></div>
		</div>
		<div id="image-container">
			<!--<div>&nbsp;</div>-->
					<script>
					$('#image-container').crossSlide({
					  speed: 35,
					  fade: 1
					}, [			  
					  { src: '/common/img/header/loa4.jpg', dir: 'up' }, 
					  { src: '/common/img/header/loa4.jpg', dir: 'down' }, 
					  { src: '/common/img/header/loa4.jpg', dir: 'up' }, 
					  { src: '/common/img/header/loa4.jpg', dir: 'down' }, 
					  { src: '/common/img/header/loa4.jpg', dir: 'up' }, 
					  { src: '/common/img/header/loa4.jpg', dir: 'down' }			  
					]);
					
					</script>		
		</div>
	</div>