INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('homepage_bsea', '', 'bsea homepage', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='homepage_bsea'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='homepage_bsea'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('content_bsea', '', 'bluesea contents', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='content_bsea'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='content_bsea'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('findus_bsea', '', 'bluesea findus', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='findus_bsea'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='findus_bsea'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('services_bsea', '', 'bluesea services', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='services_bsea'), 'detail.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='services_bsea'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('contatti_bsea', '', 'bluesea contactus', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contatti_bsea'), 'send.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contatti_bsea'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contatti_bsea'), 'mail_contactus.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contatti_bsea'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contatti_bsea'), 'init2.inc', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='search');
DELETE FROM template_disponibili WHERE dir_template='search';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('search', '', 'search', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_all.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_news.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init2.inc', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter');
DELETE FROM template_disponibili WHERE dir_template='newsletter';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('newsletter', '', 'newsletter', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter'), 'newsletter.asp', 1);
INSERT INTO `module_portal` (`keyword`, `descrizione`, `version`, `active`) VALUES ('blue-sea-theme', 'blue-sea theme installation', '1.5.5.3', '1');