INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('ads-content_bhn', '', 'bhn ads-content', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'list.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'mail.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'init2.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='ads-content_bhn'), 'init3.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('base-list-img_bhn', '', 'bhn base-list-img', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-list-img_bhn'), 'list.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-list-img_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-list-img_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-list-img_bhn'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('base-social_bhn', '', 'bhn base-social', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-social_bhn'), 'list.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-social_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-social_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='base-social_bhn'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('contact_bhn', '', 'bhn contact', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contact_bhn'), 'send.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contact_bhn'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contact_bhn'), 'mail.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contact_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='contact_bhn'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('download_bhn', '', 'bhn download', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_bhn'), 'download.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_bhn'), 'popup_download.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='download_bhn'), 'init1.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('googlemap-content_bhn', '', 'bhn googlemap-content', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-content_bhn'), 'list.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-content_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-content_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-content_bhn'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('googlemap-product_bhn', '', 'bhn googlemap-product', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'index.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'init2.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'ajaxcheckprodavailability.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'ajaxcheckprodqta.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='googlemap-product_bhn'), 'ajaxuploadfile.asp', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter');
DELETE FROM template_disponibili WHERE dir_template='newsletter';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('newsletter', '', 'newsletter', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='newsletter'), 'newsletter.asp', 1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('product_bhn', '', 'bhn product', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'index.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'detail.asp', 2);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'init2.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'ajaxcheckprodqta.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='product_bhn'), 'ajaxuploadfile.asp', -1);
DELETE FROM page_x_template WHERE id_template=(SELECT distinct(id) FROM template_disponibili WHERE dir_template='search');
DELETE FROM template_disponibili WHERE dir_template='search';
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('search', '', 'search', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_all.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'result_search_news.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='search'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('voucher-module_bhn', '', 'bhn voucher-module', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module_bhn'), 'send.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module_bhn'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module_bhn'), 'mail.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module_bhn'), 'init2.inc', -1);
INSERT INTO template_disponibili (dir_template, template_css, descrizione, base_template, order_by, elem_x_page) VALUES('voucher-module-friend_bhn', '', 'bhn voucher-module-friend', 0, 1, 5);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module-friend_bhn'), 'send.asp', 1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module-friend_bhn'), 'confirm.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module-friend_bhn'), 'mail.asp', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module-friend_bhn'), 'init1.inc', -1);
INSERT INTO page_x_template (id_template, file_name, page_num) VALUES((SELECT distinct(id) FROM template_disponibili WHERE dir_template='voucher-module-friend_bhn'), 'init2.inc', -1);
INSERT INTO `module_portal` (`keyword`, `descrizione`, `version`, `active`) VALUES ('econemesys-theme', 'econemesys theme installation', '1.5.5.3', '1');